# Ctrl+b -> Ctrl+Space
unbind C-b
set -g prefix C-Space
bind C-Space send-prefix

# Split window using new hotkeys
unbind '"'
unbind %
bind '\' split-window -h -c "#{pane_current_path}"
bind - split-window -v -c "#{pane_current_path}"

#bind-key -n C-t new-window
#bind-key -n C-w kill-window
# bind-key -n C-Tab next-window

# Set fast reload
bind r source-file ~/.tmux.conf \; display "Config reloaded!"

# Set fast switch panel to Alt + Arrow
#bind -n M-Left select-pane -L
#bind -n M-Right select-pane -R
#bind -n M-Up select-pane -U
#bind -n M-Down select-pane -D

bind h select-pane -L
bind l select-pane -R
bind k select-pane -U
bind j select-pane -D

# Enable mouse
set -g mouse on

set-option -g allow-rename off

# Start with first panel
set -g base-index 1
setw -g pane-base-index 1

setw -g mode-keys vi

unbind -T copy-mode-vi Space
unbind -T copy-mode-vi Enter

bind -T copy-mode-vi v send-keys -X begin-selection
bind -T copy-mode-vi y send-keys -X copy-pipe-and-cancel "xclip -selection clipboard -in"
bind-key -T copy-mode-vi MouseDragEnd1Pane send-keys -X copy-pipe-and-cancel "xclip -selection clipboard -in"


set-option -g history-limit 30000
#bind -T copy-mode-vi r send-keys -X rectangle-toggle 
#bind -t copy-mode-vi Escape cancel
# don't do anything when a 'bell' rings
#set -g visual-activity off
#set -g visual-bell off
#set -g visual-silence off
#setw -g monitor-activity off
#set -g bell-action none

# clock mode
#setw -g clock-mode-colour red

# copy mode
#setw -g mode-style 'fg=black bg=red bold'

# panes
#set -g pane-border-style 'fg=red'
#set -g pane-active-border-style 'fg=yellow'

# statusbar
#set -g status-position bottom
#set -g status-justify left
#set -g status-style 'fg=red'

#set -g status-left ''
#set -g status-left-length 10

#set -g status-right-style 'fg=black bg=yellow'
#set -g status-right '%Y-%m-%d %H:%M '
#set -g status-right-length 50

#setw -g window-status-current-style 'fg=black bg=red'
#setw -g window-status-current-format ' #I #W #F '

#setw -g window-status-style 'fg=red bg=black'
#setwcsetw -g window-status-format ' #I #[fg=white]#W #[fg=yellow]#F '

#setw -g window-status-bell-style 'fg=yellow bg=red bold'

# messages
#set -g message-style 'fg=yellow bg=red bold'

set -g default-terminal "tmux-256color"
set -as terminal-features ",xterm-256color:RGB"
set -g status-style bg=default,fg=white

# Левая часть: Имя сессии
set -g status-left "#[fg=blue,bold] #S #[default] "

# Список окон: активное выделяем цветом
# set -g window-status-current-format "#[fg=#ff9e64,bold] ● #I:#W #[default]"
set -g window-status-current-format "#[bg=#3b4261,fg=#7aa2f7,bold] ● #I:#W  #[default]"
set -g window-status-format "#[fg=brightblack] ○ #I:#W #[default]"

# Правая часть: время и дата
set -g status-right "#[fg=cyan] %H:%M #[fg=brightblack]| #[fg=white]%d-%b-%y "

# Рамки панелей (сделай их тонкими и неяркими)
set -g pane-border-style fg=brightblack
set -g pane-active-border-style fg=#3b4261

set -g message-style "fg=#7aa2f7,bg=#16161e" 

set -g repeat-time 800

bind-key -r C-h resize-pane -L 4 
bind-key -r C-j resize-pane -D 4 
bind-key -r C-k resize-pane -U 4 
bind-key -r C-l resize-pane -R 4 
