font_family      JetBrains Mono 
bold_font        auto
italic_font      auto
bold_italic_font auto

# Эталонный размер это 10.5, но возникается проблема, когда в nvim хочу засплитить. Буду тестить и делать меньше
font_size 9

# background #282828
# foreground #ebdbb2
# color0 #00ff00
# color7 #ff0000

background_opacity 0.935 

shell_integration no-cursor 
# cursor #cccccc
cursor_shape block
cursor_trail 1 


# BEGIN_KITTY_THEME
# Gruvbox Dark Soft
include current-theme.conf
# END_KITTY_THEME
#

hide_window_decorations YES
